language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI=true
script:
  - npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: storybook-static
  on:
    branch: test-travis
  

  # github_token  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