language: node_js
node_js: 
  - "stable"
cache: 
  directories:
before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"
  - node_modules
# env: 
#   - CI=true
script: 
  - npm run build-storybook
deploy: 
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: storybook-static
  target-branch: test-travis
  on: 
    branch: test-travis




  # github_token  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
