version: 2
jobs:
  build:
    docker: #执行容器
      - image: circleci/node:10 #依赖环境
    branches: #分支
      only:
      - test-travis
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - run: 
          name: Install
          command: console.log('installing ...')
      - run: 
          name: Test
          command: console.log('Test ...')